services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8081}:8080"
      - "5005:5005" # Debug port
    env_file:
      - ${ENV_FILE}
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit to 0.5 CPU cores
          memory: 512M # Limit to 512MB RAM
        reservations:
          cpus: "0.2" # Reserve 0.2 CPU cores
          memory: 256M # Reserve 256MB RAM
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo-network

  mysql:
    image: mysql:8.0
    env_file:
      - ${ENV_FILE}
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit to 0.5 CPU cores
          memory: 512M # Limit to 512MB RAM
        reservations:
          cpus: "0.2" # Reserve 0.2 CPU cores
          memory: 256M # Reserve 256MB RAM
    volumes:
      - /var/lib/mysql/dev_mysql_data:/var/lib/mysql
    networks:
      - todo-network
    healthcheck: # 添加健康检查
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

networks:
  todo-network:
    driver: bridge
